data_type: image
repo_path: /federated

recreate_dataset: false

batch_size: 32
test_batch_size: 100
lr: 0.1
momentum: 0.9
decay: 0.0005
total_rounds: 999
save_on_epochs: []
optimizer: SGD
multi_gpu: false

save_model: true

# parameters for Federated Learning
aggregation_type: averaging
### averaging or median
number_of_total_participants: 100
no_models: 10
retrain_no_times: 2
eta: 1

diff_privacy: false
s_norm: 15
sigma: 0.01

log: True
tb: True
random: False